### ISSUE TITLE
Check Feedback/Issues

### ISSUE THREAD

**Issue by ghost** [ItemMeta/JI#20]
Posting on behalf of [iReebok](http://www.mc-market.org/members/28725/).

- Spider check needs to be improved, doesn't notify anything.
- Jesus check is bypassable, doesn't even alert once.
- No fall check is bypassable, doesn't alert once.
- Phase check is bypassable, fence gates is easy. If full block, it will alert for speed.

**Checks:**
```
Kill Aura (Type A):
  max-vl: 5
  autoban: false
  enabled: true
Kill Aura (AimBot):
  max-vl: 5
  autoban: false
  enabled: true
Kill Aura (Type C):
  max-vl: 5
  autoban: false
  enabled: false
Kill Aura (Click Pattern):
  max-vl: 5
  autoban: false
  enabled: false
Kill Aura (Type E):
>No alerts.

Velocity (Vertical):
  max-vl: 5
  autoban: false
  enabled: true
>Needs to be redone, doesn't alert.

  
  Crits:
  max-vl: 5
  autoban: true
  enabled: true
>Needs to be redone, doesn't alert.

ReachNew:
  max-vl: 5
  autoban: false
  enabled: true
>Needs to be redone, doesn't alert.

Timer:
  max-vl: 5
  autoban: false
  enabled: true
>Needs to be redone, doesn't alert.
```
